### ISSUE TITLE
OGG decoder is not working.

### ISSUE THREAD

**Issue by Yuyi** [chris-rudmin/Recorderjs#34]
I want to decode ogg and play it.
but I only got noise :(
what's wrong with my code or decoder?

```
function decodeOgg(blob) {
  chunks = [];
  var worker = new Worker('oggopusDecoder.js');

  worker.postMessage((new Recorder).config); // uses same config as for recording
  worker.addEventListener("error", function(e) {
      console.log(e);
  });

  worker.addEventListener("message", function(e) {
      console.log(e.data);
      chunks += e.data;
  });

  var reader = new FileReader();
  reader.onload = function(event) {
      worker.postMessage({
          command: "decode",
          pages: new Uint8Array(this.result)
      });
  };

  reader.readAsArrayBuffer(blob);

  setTimeout( function() {
  var audioCtx = new (window.AudioContext || window.webkitAudioContext)();
  var source = audioCtx.createBufferSource();
  audioBuffer = audioCtx.createBuffer( 1, chunks.length, audioCtx.sampleRate );
  audioBuffer.getChannelData( 0 ).set( chunks );
  source.buffer = audioBuffer;
  source.connect(audioCtx.destination);
  source.start();
  }, 5000);

}
```

**Comment by chris-rudmin** [comment]
A few things could be wrong.

1. Is your file opus encoded and not multi-channel?
2. It seems strange to init the decoder with a property of a recorder instance. Why this way?.
3. decoding is asynchronous, you should do your buffer playback inside the message callback instead of using 5 second timeout.
4. In the message callback `e.data` is actually an array containing arrayBuffers per channel. What happens when you sum two arrays?
5. Did you have a look yet at my [decoder example](https://github.com/chris-rudmin/DecodeToWav/blob/master/example.html)?

**Comment by Yuyi** [comment]
I screwed my test code up. sorry...

Your decoder example is working :D
Thank you very much!!
