### ISSUE TITLE
Question: Stream Audio Data

### ISSUE THREAD

**Issue by mkdbns** [chris-rudmin/Recorderjs#7]
Thanks so much for this great library! One question: Would it be possible to stream the encoded audio data to a server as it's being recorded? If so, any guidance would be appreciated.

**Comment by chris-rudmin** [comment]
It is completely possible. I assume you want a ogg encapsulated stream? You will definitly need some code changes to do this.
1. On start message you will want to build the ogg headers (2 pages) and publish them with an event.
2. You would probably want to call segmentPackets() with the packet data after each buffer is encoded and publish an event when a page is completed. Look in oggopus.js, the data entry point is record buffers.

**Comment by chris-rudmin** [comment]
I just made a branch where i'll commit changes regarding streaming.
https://github.com/chris-rudmin/Recorderjs/tree/opus-stream

**Comment by mkdbns** [comment]
That's AWESOME!! I have to crash for an early wake-up but promise to review
it in the AM. I really appreciate you jumping on this so fast!

**Comment by chris-rudmin** [comment]
Try out the opus-stream branch. You should get a dataAvailable event when each ogg page is ready.
I don't have a server to receive a stream so I can't test this.

**Comment by mkdbns** [comment]
Thanks Chris!  Will do! I'll let you know how I goes.

**Comment by chris-rudmin** [comment]
I added a latency control to the stream if you use { stream : true, maxBuffersPerPage: 5 }
10 buffers per page is about 1 second of latency at 44100 Hz, Reducing this too low, will increase data and processing overhead.  Let me know how your streaming works.

**Comment by chris-rudmin** [comment]
Merged the streaming code

**Comment by Kequc** [comment]
It seems that since the last time I checked you've made a lot of amazing changes to the package! I'd like to upgrade but I rely on the streaming audio feature. The stream config option remains, but it is never used anywhere in the code.

I've tried working backwards through the changes which may have disabled the functionality unfortunately I'm falling short of achieving my goal. Is there any chance to reinstitute this feature?

**Comment by chris-rudmin** [comment]
The encoder streams by default now.  To access each stream page now, you can define `recorder.onPageEncoded` which is where each page is stored after being encoded. If you need some more details I can help.

**Comment by chris-rudmin** [comment]
@kequc, I added the option back as streamPages

**Comment by Kequc** [comment]
Man. You must know this software inside and out, it looks and works fantastic. I wasn't sure what to do with the information you gave me thank you for your help.

**Comment by genabotpub** [comment]
Hello Chris, I am new to your library so I apologize for the following basic question.

I am using an AnayzierNode to detect silence in the user's speech. Upon the silence detection I want to capture the blob that was recorded since the last silence event only (i.e. not from the beginning of the recording). The blob that I capture should be valid OGG (i.e. header info, etc.) since it is processed as such by a back-end server.

What would be the best approach to implement such a workflow using you library?

Thank you very much,
gena

P.S. I tried to implement it but having some difficulties, I was hoping you can point me to the right direction.

**Comment by chris-rudmin** [comment]
Should be possible. What part of your implementation are you having difficulties with?

**Comment by genabotpub** [comment]
Chris, thank you very much for the prompt response. I am not a specialist in audio processing, so I apologize if my comments are very basic.

Encoder Options:
•	encoderApplication: 2048
•	reuseWorker: true

Environment:
•	Win 10
•	Chrome 73
•	Mic

It seems that there is no method similar to MediaRecorder.requestData() to proactively trigger ondataavailable callback with a complete (playable) blob. Therefore, I need to call stop()/start() every time I detect silence.

Since, calling stop() kills/cleans audio context provided by the start() function I do not pass streamNode [audioContext.createMediaStreamSource(stream)] I use to connect my AnalyzerNode. Because otherwise the silence detection will work only once.

Issue:
Although the above logic works and returns playable blobs, for some reason each subsequent blob includes fainted audio of the previous blobs that were detected. 

Questions:
1.	Is there a better approach than using stop/start to achieve my objective?
2.	Do you know what could cause the issue I described?

Thank you very much,
gena

**Comment by chris-rudmin** [comment]
The recorder API doesn’t do what you need. You will need to create your own implementation which calls encoder worker directly with the buffers you want.

**Comment by genabotpub** [comment]
Thank you.
