### ISSUE TITLE
AudioContext/node not being cleaned up

### ISSUE THREAD

**Issue by DigitalZebra** [chris-rudmin/Recorderjs#92]
Hi! Thanks so much for this project/library!

It doesn't look like the recorder's `audioContext` and `sourceNode` are getting cleaned up properly after stopping a recording session. If you create many recordings on the same page, you'll get the following error in Chrome after 6 recordings: 
`Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6).`

I was able to fix this for my use case by doing the following after calling `stop()`:

```
	this.recorder.stop();

	if (this.recorder.sourceNode) {
		this.recorder.sourceNode.disconnect();

		if (this.recorder.sourceNode.mediaStream) {
			this.recorder.sourceNode.mediaStream.getTracks()[0].stop();
		}
	}

	if (this.recorder.audioContext) {
		this.recorder.audioContext.close();
	}
```

I'm thinking that the `stop()` method should be the one to clean up the context/node as a single recorder instance is only meant to be used once, correct?

**Comment by chris-rudmin** [comment]
The source node gets cleaned up if `recorder.clearStream()` is called. This should occur by default on event `stop`.

The audioContext is supposed to stay alive as long the recorder instance is alive. 

The recorder instance can be used many times. A new one is not required for each recording, only if you want to change the config parameters. The expected behaviour is if you delete the recorder instance or dereference it, then it should be garbage collected.  But perhaps this is not occurring if the audio context is not closed.  Something to test out.

**Comment by DigitalZebra** [comment]
Thanks! I rearranged my code to re-use the recorder instance and everything seems to be working as expected after your suggestions.

I do think that some sort of change may be required that will explicitly clean up the audioContext if a client desires to create multiple new Recorder instances on the same page.

Thanks again for the help, I'll close this issue!
